### PR TITLE
Feature: Gentoo tweaks

### PR DESCRIPTION
**Pull request by xgqt**
- support Portage
- support VERSION_ID used in os-release in Gentoo systems
- misc run_from_source.py tweaks

### CODE REVIEW

**Comment by hakandundar34coding** [comment]
Support for number of portage packages is added manually. The pull request will be closed. Currently, there are no plans for new features.

**Comment by xgqt** [comment]
> Support for number of portage packages is added manually. The pull request will be closed. Currently, there are no plans for new features.


Hi @hakandundar34coding !

> Support for number of portage packages is added manually.

I do not quite understand, what do you mean by "added manually"?

Could you check out any other changes I submitted here?
Maybe they can be reused in a different PR.

Thanks.

**Comment by hakandundar34coding** [comment]
@xgqt

The project is ended. There will not be new versions. I wanted to add the package count feature only. But there were several changes in your pull request. But this time your name is not shown in the contibutors list. You can send a pull request for the changes in `run_from_source.py: define main` commit if you want your name to appear in the contibutors [list](https://github.com/hakandundar34coding/system-monitoring-center/graphs/contributors).

Changes about version ID overwrites os version information. `run_from_source.py` may be used in Flatpak folders for running the application by using system Python in the installation directory. I did not want to remove it from the `sources` list.

If you have additional questions, do not hesitate to ask them.

**Comment by xgqt** [comment]
> @xgqt
> 
> The project is ended. There will not be new versions. I wanted to add the package count feature only. But there were several changes in your pull request. But this time your name is not shown in the contibutors list. You can send a pull request for the changes in `run_from_source.py: define main` commit if you want your name to appear in the contibutors [list](https://github.com/hakandundar34coding/system-monitoring-center/graphs/contributors).
> 
> Changes about version ID overwrites os version information. `run_from_source.py` may be used in Flatpak folders for running the application by using system Python in the installation directory. I did not want to remove it from the `sources` list.
> 
> If you have additional questions, do not hesitate to ask them.



> I wanted to add the package count feature only.

That is not a problem at all. There are several ways to get the commits that only introduced the portage support. Off top of my head I would merge the changes locally, not via GitHub(!), and then remove unwanted commits.

> Changes about version ID overwrites os version information.

Oh, yea you are right, to prevent that we would have to check if os_version already has something, but I guess lines may be in random order? So this commit we can throw out to not overwrite os_version.

> run_from_source.py may be used in Flatpak folders for running the application by using system Python in the installation directory. I did not want to remove it from the sources list.

Interesting, I did not think about Flatpak at the time.

**Pull request closed without merging**
