### PR TITLE
Fix #9

### LINKED ISSUE #9: Processes not showing in Manjaro Linux
Throws an error in the terminal:
```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Processes.py", line 369, in processes_loop_func
    username = usernames_username_list[usernames_uid_list.index(real_user_id)]
ValueError: '62582' is not in list

```

### PR DESCRIPTION
**Pull request by keyiflerolsun**
Fix #9 Issue 🕊

### CODE REVIEW

**Comment by hakandundar34coding** [comment]
Length of the ```username_list``` have to be same with number of processes. Otherwise, this will cause problems. ```-``` or ```UID:[uid_number]``` value may be used as username (string value).```try-except``` hides error and code continues to run. A username string have to be added to ```username_list``` list.

I will ask the user (who reported the bug) what is the username of this process on system default task manager.

More information may be required to solve this problem.

**Comment by keyiflerolsun** [comment]
> Length of the `username_list` have to be same with number of processes. Otherwise, this will cause problems. `-` or `UID:[uid_number]` value may be used as username (string value).`try-except` hides error and code continues to run. A username string have to be added to `username_list` list.
> 
> I will ask the user (who reported the bug) what is the username of this process on system default task manager.
> 
> More information may be required to solve this problem.

image

same things

**Comment by hakandundar34coding** [comment]
This one can be used if process is ended just after first check. The purpose is here to make list length same with the number of processes. I do not know if the problem is about ```ended process```. Do you know? Do you have the same problem? I could not find any problems on Manjaro Linux on virtual machine.

**Comment by keyiflerolsun** [comment]
yes, i faced this error regardless of sudo or non sudo user. I guess because thread is used, it causes the process list to change constantly.

**Pull request closed without merging**
