### PR TITLE
Change Russian localization files

### PR DESCRIPTION
**Pull request by akorny**
I've managed to run application with `ru_RU` locale and, as promised, I double checked the localization and made some changes.

### CODE REVIEW

**Comment by hakandundar34coding** [comment]
Can you check `Chart - Show` and `Masked` values?
You can translate the first one as separate words. Not as "showing the chart".

**Comment by akorny** [comment]
I kinda don't get what `Chart - Show` means in the context of toggling the variants of graphics. For me, heading `Chart view` or `Chart type` for this setting group makes more sense. That's why I translated it as `Вид графика`. `Вид графика` from Russian translates as `Chart type` or `Chart view` (there are two translation variants for word `вид` in this context). 

`Masked` translations looks legit for me either. I found an example of similar translation in `DigitalOcean`'s `systemctl` tutorial in Russian. In this tutorial `mask` is translated as `маскировать`.

**Comment by hakandundar34coding** [comment]
I do not know Russian language. I have checked some text. "Masked" was translated as "Maxed out". It was interesting. Translation tool may translate wrong.

**Comment by akorny** [comment]
So, do I need to translate `Chart - Show` as separate words? For me, as a Russian native speaker, translation that I provided would make more sense than this two words separate translation.

**Comment by hakandundar34coding** [comment]
It can be leaved without change.
Meaning of `Graph - Show` and `Graph View` are not very different. In the menu they have slightly different meanings.

What about `Masked` and `Maxed Out`? Is translation from online translation tool wrong?

**Comment by akorny** [comment]
Yes, it is wrong.

**Comment by hakandundar34coding** [comment]
I will merge this pull request. Russian translation text will be included in the new package (v1.18.0). It will be downloadable tomorrow.

**Pull request merged**
