### PR TITLE
Small changes in the pt-BR translation

### PR DESCRIPTION
**Pull request by eusouobn**

### CODE REVIEW

**Comment by hakandundar34coding** [comment]
After a quick check there are 3 notes:

1) Is ```Velocidade/Frequência``` translation of ```Manufacturer``` text?

   I do not know your language but some words are similar to their English translations.

2) There are two different information in this text ```Version - Code Name:```. But there may not be translation of ```Code Name``` in your language.

3) ```Frequência Min - Max:``` may be modified as ```Frequência Min-Max:``` because it is a very long text. I did not used spaces in English because it was very long.

I will merge the pull request after your review.

**Comment by eusouobn** [comment]
1 - Yes, the first time I uploaded the file, this mistake happened, and I
only realized it later, so this is now fixed...

2 - I asked friends for opinions about the "Code Name" part and they
suggested I put "Codenome" so I will do that...

3 - Ok I will modify the "Frequency min - max" to leave it with no spaces...

And I changed the name of the Software from "Center" to "Central", because
everyone agreed that it would be better

Em qui., 24 de mar. de 2022 02:42, Hakan Dündar ***@***.***>
escreveu:

**Comment by eusouobn** [comment]
Now I just need to change the name inside the .desktop file and I'm not
finding it

Em qui., 24 de mar. de 2022 às 02:42, Hakan Dündar ***@***.***>
escreveu:

**Comment by hakandundar34coding** [comment]
The ```.desktop``` file is in the ```/integration``` folder. Latest pull request is merged. Latest source code contains the updated translation. It will be used in a newer release.

You can also reply/write comments on Github page. System sends emails to you if there are comments.

**Comment by eusouobn** [comment]
OK I made the modification and opened the PR...
Thanks a lot for the help

Have a great day

Em qui., 24 de mar. de 2022 às 11:32, Hakan Dündar ***@***.***>
escreveu:

**Pull request closed without merging**
