### PR TITLE
allow for building for deb and pip in master branch

### PR DESCRIPTION
**Pull request by theofficialgman**
makes deb_for_stores branch unnecessary

this assumes the deb is built with

```
sudo debian/rules binary-indep
```

in which case the arguments passed to setup.py are always either "config" "build" or "install"

pip passes the args "egg_info" "dist_info" and "bdist_wheel" meaning the the else will be used for pip installs

if you have a better idea for detecting the presence of pip vs debhelper, let me know

the purpose of this PR is to lessen the maintenance burden and allow github actions CI building if you wish to have it

### CODE REVIEW

**Comment by theofficialgman** [comment]
from what I could observe, the only changes between the deb_for_stores and master branch were the lack of `debian` folder and the `setup.py` differences.

**Comment by hakandundar34coding** [comment]
@theofficialgman 
> from what I could observe, the only changes between the deb_for_stores and master branch were the lack of debian folder and the setup.py differences.

`debian` folder and `setup.py` file are the only changes as you write.

I used a single setup.py file for debian, rpm, pacman packages a long time ago. After switching to pip package I used separate setup.py files. The reason for separate setup.py files:

A package maintainer may want to add this package into repositories of a distribution and a simpler and separate setup.py file may require less effort for this operation. Currently the application has low download numbers and it is not included to repositories. Probably, many of the deb package downloads are from Pi-apps (including the update numbers).

I thought searching about copying the files in the main branch to deb branch and preparing a deb package by using github instead of copying all the files in the local machine and uploading them to deb branch. But I did not have time for that.

**Comment by hakandundar34coding** [comment]
@theofficialgman

Checks may be performed for deb packaging instead of pip packaging. Can you update the setup.py file? You can ignore this if it takes very much time.

What are the risks when some parameters are checked for detecting the packaging type?
Are these parameters changed/updated very frequently?

**Comment by theofficialgman** [comment]
> What are the risks when some parameters are checked for detecting the packaging type? Are these parameters changed/updated very frequently?

to my knowledge the parameters have not changed at all.
https://manpages.debian.org/testing/dh-python/pybuild.1.en.html

I believe that setup.py from pip is now legacy functionality (as of very recently and will still be supported). you can see that the commands pip calls are also standardized here: https://pip.pypa.io/en/stable/reference/build-system/setup-py/#setup-py-legacy
It does appear that if `bdist_wheel` fails, then pip will call `install` to setup.py which is not ideal as this is also used for deb creation.

**Comment by hakandundar34coding** [comment]
@theofficialgman

I merged this pull request. But the changes are reverted. Because some changes for ArchLinux packages also required. Currently a change is not required. Because development speed of the application will be slower. There will be new updates less frequently.
But bugs will be fixed without waiting a long time.

Additionally:
I did not want to cancel the pull request. Because you spent a lot of time for new features and fixes.

**Pull request merged**
